version: '3.3'

# Configure a mode_modules volume so that we can cache the node_modules so we don't have to install them on each rebuild.
volumes:
  client_node_modules:
  truffle_node_modules:

# Configure the network strategy for linking your containers.
networks:
  app_network:
    driver: bridge

# Declare the container block
services:
  # Configure the app container for local development
  client:
    depends_on:
      - ganache
    build: client
    networks:
      - app_network
    volumes:
      - client_node_modules:/app/node_modules
      - ./ethereum/build/contracts:/app/lib/contracts
      - ./client:/app
    ports:
      - 3000:3000
    environment:
      PROVIDER_URI: http://ganache:8545
    command: "yarn dev"
  truffle:
    build: ethereum
    networks:
      - app_network
    volumes:
      - truffle_node_modules:/app/node_modules
      - ./ethereum:/app
    environment:
      RPC_HOST: ganache
      HDWALLET_MNEMONIC:
      INFURA_ACCESS_TOKEN:
  ganache:
    image: trufflesuite/ganache-cli
    networks:
      - app_network
    ports:
      - 8545:8545
    environment:
      HDWALLET_MNEMONIC:
    command: "-m ${HDWALLET_MNEMONIC}"
